[package]
name = "blockchain_pow"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
sha2 = "0.10.0"
serde = "1.0.117"
serde_json = "1.0.74"
hex-literal = "0.3.4"